[project]
name = "decode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flax>=0.10.2",
    "jax>=0.5.0",
    "pre-commit>=4.1.0",
]
